spring.mail.host=${CATS_MAIL_HOST}
spring.mail.port=${CATS_MAIL_PORT:587}
spring.mail.username=${CATS_MAIL_USER}
spring.mail.password=${CATS_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=3000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=3000
